package com.reqpilot.ai;

public enum AiErrorType {
  INVALID_API_KEY,
  PAYMENT_REQUIRED,
  OPENROUTER_RATE_LIMIT,
  PROVIDER_RATE_LIMIT,
  PROVIDER_OVERLOADED,
  PROVIDER_UNAVAILABLE,
  TIMEOUT,
  INVALID_RESPONSE,
  UNKNOWN
}
